In [3]:
import pandas as pd
import numpy as np

In [40]:
print(pd.__version__)

2.1.4


In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-20 13:29:40--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.1s    

2024-09-20 13:29:41 (2.40 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [5]:
df=pd.read_csv('laptops.csv')

print(df.head())


                                              Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.

In [6]:
#How many records in dataset?
row_count = len(df)
print(row_count)

2160


In [7]:
#How many laptop brands are presented in the dataset?
count_laptop_brands = df['Brand'].nunique()
print(count_laptop_brands)


27


In [8]:
#How many columns in the dataset have missing values?
count_missing_columns = df.isnull().any().sum()
print(count_missing_columns)


3


In [9]:
#What is the maximum final price of Dell notebooks in the dataset?
max_dell_price = df[df['Brand'] == 'Dell']['Final Price'].max()
print(max_dell_price)

3936.0


In [10]:
#Median Value of Screen Column in the dataset
median_screen_val = df['Screen'].median()
print(median_screen_val)

#Calculate the most frequent value of the same Screen Column
most_freq_val_screen=df['Screen'].mode()[0]
print(most_freq_val_screen)

#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step
df['Screen'].fillna(most_freq_val_screen,inplace=True)

#Now calculate the median value of Screen Once afgain
new_median_screen_val = df['Screen'].median()

print(new_median_screen_val)

15.6
15.6
15.6


In [11]:
#Select all the INNJOO laptops from the dataset
df[df['Brand']=='Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [12]:
#Select only columns RAM, Storage,Screen
df[['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]

In [13]:
print(df.columns)

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')


In [22]:
#Get the underlying NumPy array. Let's call it X
X = df[df['Brand']=='Innjoo'][['RAM', 'Storage', 'Screen']].values
X


array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [33]:
#Matrix-Matrix Computation of X and the Transpose of X
XTX = X.dot(X.T)
XTX


array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

In [36]:
np.linalg.pinv(XTX)

array([[ 0.07685672, -0.03540126, -0.12193106,  0.04199099,  0.0139265 ,
         0.0139265 ],
       [-0.03540126,  0.01651252,  0.05568098, -0.01960876, -0.00663032,
        -0.00663032],
       [-0.12193106,  0.05568098,  0.19459549, -0.0659823 , -0.02157929,
        -0.02157929],
       [ 0.04199099, -0.01960876, -0.0659823 ,  0.02329208,  0.00789214,
         0.00789214],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294]])

In [17]:
#Create an array y with values ....
y=np.array([1100,1300,800,900,1000,1100])

In [38]:
#Multiple the inverse of XTX with the transpose of X and then multiply the result by y.
w = X.T.dot(np.linalg.pinv(XTX)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])